[ExcludeEngineContent]
; Target specific platforms or leave blank for all
Platforms=Win64
Targets=Development
bExcludeFromPaks=true
; Use regex to block anything starting with the Engine path
+Files="../../../Engine/*"
